### ISSUE TITLE
Layerにマウスオーバーしている状態でhintを更新してもWindow.onHintChanged() が呼ばれない

### ISSUE THREAD

**Issue by YunYunDetective** [krkrz/krkrz#113]
Layerにマウスオーバーしている状態で当該レイヤのhintを更新
してもWindow.onHintChanged() が呼ばれません。

吉里吉里に動作を準拠する場合、hintを更新したタイミングで
Window.onHintChanged() が呼ばれる必要があります。

**Comment by jin1016** [comment]
私の方で修正確認後長期間放置されているようなのでcloseしてしまいます。
