### ISSUE TITLE
モーダルウィンドウでマウスホイールイベントを受け取れない

### ISSUE THREAD

**Issue by YunYunDetective** [krkrz/krkrz#114]
showModal() で表示したWindowのLayerでonMouseWheele()にマウスホイールイベントが飛んで来ない。

**Comment by jin1016** [comment]
フォーカスが得られず一連の不具合が発生していると言うことなので修正。
https://github.com/krkrz/krkrz/tree/fix178
EnableにしてからShowするようにした。
これで直っているはず。

**Comment by jin1016** [comment]
私の方で修正確認後長期間放置されているようなのでcloseしてしまいます。
