### ISSUE TITLE
非クライアント領域や別のウィンドウ上でWindow.hideMouseCursor()が機能してしまう

### ISSUE THREAD

**Issue by miahmie** [krkrz/krkrz#164]
タイトルバーやボーダー・メニューバー上にマウスカーソルがある状態で
Window.hideMouseCursor()を呼ぶと，クライアント領域にマウスを移動させるまで
マウスカーソルが消えた状態になってしまう（カーソルを動かしても表示が復帰しない）

もしくは別のWindowインスタンスBのクライアント領域上にマウスカーソルがある状態で
WindowインスタンスAのhideMouseCursor()を呼ぶと，
インスタンスBのボーダーに移動するまでマウスが消えたままになる。

吉里吉里２では，そのWindowインスタンスのクライアント領域上にマウスカーソルがある時しか機能しない。

再現例：
```javascript
function CreateWindow(name, w=320, h=240, border=bsSingle) {
	var win = new Window();
	win.caption = name;
	win.borderStyle = border;
	win.setInnerSize(w, h);
	win.add(new Layer(win, null));
	win.primaryLayer.setSize(w,h);
	win.primaryLayer.visible = true;
	win.visible = true;
	return win;
}
var win1 = CreateWindow("HideMouseCursorTestWindow");
win1.onKeyDown = function(key) {
	switch (key) {
	case VK_SPACE:  hideMouseCursor(); break;
	case VK_RETURN: Debug.message(mouseCursorState, 
		@"visible=${mcsVisible}, tempHidden=${mcsTempHidden}, hidden=${mcsHidden}");
		break;
	}
} incontextof win1;
var win2 = CreateWindow("SubWindow", 320,48, bsToolWindow);
```
実行してHideMouseCursorTestWindowウィンドウをクリックしてフォーカスし
タイトルバーの上にマウスカーソルを置いてスペースキーを押したり，
フォーカスそのままでSubWindow上にマウスカーソルを置いてスペースキーを押す[※]と現象を確認できる。
また，リターンキーを押すと，コンソールにmouseCursorStateが表示される。

※一度この現象を起こすと，HideMouseCursorTestWindowのクライアント領域にマウスカーソルを移動させてmouseCursorState=visible状態に戻さない限り再度同じ現象は起こせません。
（tempHidden状態ではhideMouseCursor()が無視されるためだと思われます）

**Comment by miahmie** [comment]
MouseCursor.cppを眺めていてふと思ったのですが，
カーソル変更に::SetCursorを使うのではなく，
::SetClassLongPtr(GCLP_HCURSOR)でウィンドウクラスのカーソルを変更する方法ではダメでしょうか？

**Comment by jin1016** [comment]
> カーソル変更に::SetCursorを使うのではなく，
> ::SetClassLongPtr(GCLP_HCURSOR)でウィンドウクラスのカーソルを変更する方法ではダメでしょうか？
良い悪い以前に、なぜそのように変更するのか理由がなければ意味不明です。
その変更によって本不具合が修正され、影響範囲のテストに全てパスすると言うことであればわかります。
ただ、本来は吉里吉里2とVCLのソースコードを確認し、発生する理由と吉里吉里2で発生しない理由を特定し、吉里吉里2と同じような方法へ修正するべきではないでしょうか？
もちろん、他の修正方法での動作の方がより好ましいと思われるのであれば、そちらにする方が良いと思います。

**Comment by miahmie** [comment]
クラスのカーソルを変更すれば自動的にクライアント領域のみカーソル変更の影響があるもだと思い
先のような書き込みをしました。（確認はしてません。すみません）

その後，色々調べたのですが，WM_SETCURSORメッセージを解釈するのが正しい実装のようです。
このメッセージを解釈しつつ，TJS側からマウスカーソルが変更された場合は
その時点でカーソルがクライアント領域上かどうか調べてカーソル（もしくはvisible state）を変更する
という対応が妥当かと思われます。この方向でよさそうでしたらPullRequest書いてみます…

**Comment by jin1016** [comment]
吉里吉里2+VCLはそのような実装になっているのでしょうか？
それでしたらその形で問題ないと思います。

**Comment by miahmie** [comment]
あー，VCLって（pascalだけど）ソース読めるんですね。
ブラックボックスかと思ってたので微妙に話が通じてませんでした。ごめんなさい。
で，ざっとコード読ませてもらった感じでは，
・WM_SETCURSOR(TWinControl.WMSetCursor)でHTCLIENTだったら::SetCursor呼ぶ
・VCL側からカーソル変更した場合（TScreen.SetCursor）は::SendMessageでWM_NCHITTESTの後WM_SETCURSORを呼んでカーソル変更を反映する
という流れのようです。
あと，吉里吉里２側の実装ですが，TTVPWindowForm::SetMouseCursorVisibleStateでカーソル消すときはcrNone（実質的に::SetCursor(NULL)相当）指定でカーソルを消しているみたいで，最終的には::ShowCursorは使われていない模様です（VCL側でShowCursor相当のAPIがない）。

**Comment by jin1016** [comment]
なるほど。
それであればその実装を参考に作るのが良いのではないでしょうか。
非表示は、うまく機能するのならどちらでも良いように思いますが。

**Comment by miahmie** [comment]
#170 にてPullRequest作成しました。ご確認ください。
