### ISSUE TITLE
RegExpでstartを指定して実行した際、プロパティが正しく更新されない

### ISSUE THREAD

**Issue by sakano** [krkrz/krkrz#166]
RegExpのstartが0以外のとき、matches, lastMatch, lastParenのプロパティが正しく更新されません。
マッチング自体は指定した位置から実行され正しく動作しますが、これらの結果文字列の位置がstartだけずれてしまいます。

<pre><code>var r = /^[a-z]/;
r.start = 1;
if (r.test("Abc")) {
    // testには成功するが "A" と表示されてしまう。吉里吉里2では "b"
    Debug.message(r.matches[0]);
}
</code></pre>

検索はstartの値だけ先頭をずらした文字列に対して実行されています。（tTJSNC_RegExp::Match）
よってregionに格納される検索結果は元の対称文字列から見ればstartだけずれた位置になっています。が、プロパティの値となる部分文字列を生成する際にこれが一切考慮されずregionの位置情報がそのまま使われてしまっています。（tTJSNC_RegExp::Exec, tTJSNC_RegExp::GetResultArray）
そのため結果文字列の内容がstartの数だけずれてしまっています。

部分文字列を生成する部分でもstartでずらせば解決すると思います。
検索実行時点で文字列をずらさずに検索開始位置だけずらす形にもできるようですが、 ^ を使った際の検索結果が吉里吉里2と異なってしまうため好ましくありません。

**Comment by jin1016** [comment]
確認しました。
close します。
