### ISSUE TITLE
モーダルウィンドウでIMEが使用できない

### ISSUE THREAD

**Issue by YunYunDetective** [krkrz/krkrz#178]
Window.showModal()で表示したモーダルウィンドウで、IMEによる日本語入力が出来ません。
imeModeをimeDontCareに設定しても駄目でした。

**Comment by YunYunDetective** [comment]
同様に「モーダルウィンドウでマウスホイールが取れない」と言う現象も発生していた。
そこを軸に検索してみたところ「ウィンドウのフォーカスがちゃんと移動していない」と言うことがわかった。

そこで、TVPWindow.cppの876行目付近に以下のように

`
			Application->GetEnableWindowList( enableWindows, NULL );
			Application->DisableWindows();
			Show();
			::SetActiveWindow( GetHandle() );
			SetEnable( true );
            ::SetFocus( GetHandle() );
			modal_result_ = 0;
			while( modal_result_ == 0 ) {
`

フォーカスを移動させる命令を追記したところ、マウスホイールもIMEも認識するようになりました。

**Comment by YunYunDetective** [comment]
krkrzでのウィンドウフォーカスは、以下のようにWindowFormUnit内で、
TVP_WM_RETRIEVEFOCUSメッセージを受けて処理されているので、
何らかの理由でここまでコードがたどり着いていないものと思われます。

>LRESULT WINAPI TTVPWindowForm::Proc( HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam ) {
>	switch( msg ) {
>	case TVP_WM_RETRIEVEFOCUS:
>		WMRetrieveFocus();
>		return 0;
>	}
>}
>
>void TTVPWindowForm::WMRetrieveFocus() {
>	Application->BringToFront();
>	SetFocus( GetHandle() );
>}

**Comment by jin1016** [comment]
フォーカスが得られず一連の不具合が発生していると言うことなので修正。
https://github.com/krkrz/krkrz/tree/fix178
EnableにしてからShowするようにした。
これで直っているはず。

**Comment by jin1016** [comment]
本体へマージ

**Comment by jin1016** [comment]
私の方で修正確認後長期間放置されているようなのでcloseしてしまいます。
