### ISSUE TITLE
IDR_LICENSE_TEXTのリソーステキストの末尾処理不具合

### ISSUE THREAD

**Issue by miahmie** [krkrz/krkrz#180]
MsgImpl.cpp: TVPReadAboutStringFromResource()でライセンステキストを
UTF8からUTF16に変換する処理がありますが，リソースデータはNull-terminated Stringではないので，
データによってはバッファオーバランが発生することがあります。

SizeofResourceを考慮した変換処理を行うか，一度ローカルにコピーして
Null-terminated Stringを作った上で変換するのどちらかの修正を検討ください。
（指示いただければそれに沿ったPull Requestを作成します）

なお，他のTEXTリソースはsizeを考慮して処理されているようです。

**Comment by jin1016** [comment]
これはどのように処理するか迷うところですね。
長さを指定する変換メソッドを追加して、それを使う形の方が良いでしょうか。
つまり、SizeofResourceを考慮した変換処理を行うですかね。

ビルドする人しか編集しないことを考えると、最初からUTF-16でリソースに入れておくと言う手もありますが、少し統一性がなくなってしまいますね。

**Comment by miahmie** [comment]
#181 にPullRequestを作成しました。ご確認ください。

**Comment by jin1016** [comment]
確認し、マージしました。
