### ISSUE TITLE
sprintf will crash in vs2015 build version

### ISSUE THREAD

**Issue by uiojkmm** [krkrz/krkrz#186]
test script:
System.inform("test");
System.inform("%d:%02d / %d:%02d".sprintf(1, 2, 3, 4));
System.inform("test");

-------------------
vs2015 build version and test script:
https://cloud.githubusercontent.com/assets/6312139/11559655/9445ffc8-99f5-11e5-97a0-eb9210658589.png
please rename .png to .7z

------------------
source code version:
https://github.com/krkrz/krkrz/commit/dc3be2a5cd0e1a082def53a416c5f7d034b1bb4f

------------------
demo test in windows10pro and windows7pro
same script test in vs2013 build version is success

-----------------
![20151203194543](https://cloud.githubusercontent.com/assets/6312139/11559792/84299824-99f6-11e5-873d-c4b98ad805bd.jpg)

**Comment by sakano** [comment]
Sprintf crashes because it is called with a wrong format. Although "%d" is translated into "%Ld" now, correctly it must be translated into "%I64d". For more information, please see #184.

It will be fixed when #185 is merged

**Comment by uiojkmm** [comment]
@sakano Thanks for your fix, i test it successfully!
