### ISSUE TITLE
adjustGamma の処理結果が吉里吉里2と異なる

### ISSUE THREAD

**Issue by kiyobee** [krkrz/krkrz#194]
Layer に画像等を読み込んで adjustGamma でガンマ値の変更を行うと、真っ白(0xffffff)のピクセルのみガンマ値変更の影響を受けないようです。
下記の再現コードでは、右側の薄いグレーの方のみ赤く変わります。
```
class MyWindow extends Window
{
    function MyWindow()
    {
        super.Window(...);
        setInnerSize(320, 240);
        add(new Layer(this, null));
        with(primaryLayer)
        {
            .setSize(innerWidth, innerHeight);
            var hw = .width\2;
            .fillRect(0, 0, hw, .height, 0xffffffff);
            .fillRect(hw, 0, hw, .height, 0xffcccccc);
        }
        visible = true;
    }

    function onClick()
    {
        primaryLayer.adjustGamma(1.0,,,0.0,,,0.0);
    }
}
var win = new MyWindow();

```

**Comment by kiyobee** [comment]
コード自体に変更はないですが、1.0/0.0 の解釈が異なるため(?)結果に違いが生まれているようです。
吉里吉里Zの処理結果が正しくはありますが、吉里吉里2での結果を期待している部分があるのでどうするか検討中。

**Comment by jin1016** [comment]
64bit対応で、テーブル生成をSSE/SSE2化したものでは、発生しないようです。
float -> int 変換で明示的に切り捨てを使っているからかもしれません。
上記対応が入ると直ると思いますが、C版で問題が出ることには変わりないですね。

tjsConfig.cpp/TJSSetFPUE で FPU設定をしていますが、確か例外発生有無のみ切り替えているので、他に FPU の設定を切り替えるものを追加して呼び出す形にして回避できるかもしれません。
SSE の コントロールレジスタ設定は、今のところ何もしない形になっています。

**Comment by kiyobee** [comment]
ご確認ありがとうございます。
FPU周りについても不勉強なので、お任せできればありがたいです。

**Comment by jin1016** [comment]
わかりました。
C版でも同じような結果となるように修正します。

FPU 設定等色々と試してみましたが改善せず、どうも pow の実装違いの問題のようです(SSE版は別の pow 実装)。
適当な pow 実装を探して差し替えてみると吉里吉里2と同じような結果になりました。
この部分のみ OSS の fastmath か何かに切り替えることを検討します。

**Comment by kiyobee** [comment]
なるほど、pow が原因でしたか。
では、ご検討よろしくお願いします。

**Comment by jin1016** [comment]
https://github.com/krkrz/krkrz/commit/a2bc15d7059e5a6e12e8c68d415f8bbcc1424159

pow(x, y) == exp(y * log(x))
を利用して、pow を exp と log に置き換えることで回避できたので、そのように対応しました。
ご確認ください。

**Comment by kiyobee** [comment]
吉里吉里2と同じ結果が得られることを確認しました。
ありがとうございます。
