### ISSUE TITLE
ゲーム解像度よりも小さい画面でフルスクリーン化すると正しく描画できなくなる

### ISSUE THREAD

**Issue by AknEp** [krkrz/krkrz#201]
お世話になっております。
基本的に表題の通りですが、こちらでは、FullHDのゲームをそれ以下の解像度のディスプレイで表示したときに発生しています。

↓ こんなかんじです。
<img width="1680" alt="2016-03-19 00 59 40" src="https://cloud.githubusercontent.com/assets/743292/13883816/9168390c-ed6e-11e5-9366-565c3f389576.png">
※ メッセージレイヤは調整していないだけなのですが、画像が全面表示されないのが問題です。

フルスクリーン時は `kag.setSize` も効かないので、対処法がないように思えました。
こちらでは setSize 時に GetFullScreenMode の判定をしている部分をコメントアウトし、フルスクリーン時にも必要に応じてkag.setSizeすることで対応しました。
https://github.com/4th-cluster/krkrz/commit/ba5174c398c52fadbdbe080b1d02fd2d7e12de0e

### 確認した環境

MacBook Pro Retina 13inch上のParallels Desktop 10.3.0  …の上のWindows10 ディスプレイ解像度 1440x900 で、メニューからフルスクリーンを選ぶことで再現

https://github.com/4th-cluster/kag3/tree/oversize-representation

**Comment by AknEp** [comment]
![Uploading スクリーンショット 2016-03-19 01.11.11.png…]()

**Comment by AknEp** [comment]
（すみません…操作ミスしました）

期待する画面はこうです。 1920x1200で表示したものです。

<img width="1680" alt="2016-03-19 01 11 11" src="https://cloud.githubusercontent.com/assets/743292/13884075/97dda5c8-ed6f-11e5-826a-dc345e029f50.png">

**Comment by jin1016** [comment]
fix201 ブランチにて対応。
この問題の根幹はフルスクリーン化ではなく、ウィンドウの最大サイズがプライマリーディスプレイサイズに制限されることに依存していました。
フルスクリーン化は、期待通り動作しています。

ウィンドウの最大サイズはWindow.setMaxSizeにて指定しますが、未指定の場合は0が入ります。
ドキュメントでは、「0を指定すると制限は無くなります」と書かれていますが、正確には0の時にリサイズ可能最大サイズはプライマリーディスプレイサイズが上限となります(マルチディスプレイ環境下ではすべてのディスプレイの合計となります)。
これは吉里吉里2も同様で、Windows(VCL)の仕様の認識漏れだったようです。
参照 : [MINMAXINFO structure](https://msdn.microsoft.com/ja-jp/library/windows/desktop/ms632605%28v=vs.85%29.aspx)
つまり、上限解像度が1440x900のディスプレイで1920x1080を指定すると、指定よりも小さいウィンドウで表示されます。
これは吉里吉里2も同じ動作でした。
ただ、吉里吉里Zと2の違いとして、Zはクライアント領域がそのまま描画領域となっていますが、2はPaintBoxを内包し、小さいとスクロールバーが出て表示されるようになっています。
そして、フルスクリーン化の時Zはクライアント領域を基準に拡大/縮小表示を行いますが、2はPaintBoxのサイズを基準とするため2の時は全体が表示されていました。
このクライアント領域の扱い方の仕様の違いがフルスクリーン時の動作の違いとして期待した動作ではなくなっていたようです。
フルスクリーン化の動作は意図した動作であるため、今回は上述のドキュメントと仕様の食い違いを修正することで、期待した動作となるように修正しました。
つまり、setMaxSizeで0を指定した時、リサイズ時のサイズは無制限(実際はINT_MAX)となるようにしました。

上記の通りsetMaxSizeの問題であるので、本修正なしでもsetInnerSizeを指定する時に以下のようにスクリプトを修正することで対応は可能と言えば可能です。
setMaxSize( width+100, height+100 );
setInnerSize( width, height );

ついでなので――
従来はバックバッファの最大サイズはWindowのあるディスプレイの最大サイズとしていましたが、描画領域(クライアント領域)と比較して大きい方を指定して、描画されない領域が出ないようにしました。
後、setMaxSizeで最大化時のサイズまで変更していたのを、最大化時のサイズは変更しないようにしました(2と同じ動作)。

**Comment by miahmie** [comment]
> 従来はバックバッファの最大サイズはWindowのあるディスプレイの最大サイズとしていましたが、描画領域(クライアント領域)と比較して大きい方を指定して、描画されない領域が出ないようにしました。

この問題は多分 #135 の件のことだと思いますので，修正確認できたらそちらもcloseします

**Comment by AknEp** [comment]
お世話になっております。 非常に素早い対応ありがとうございます。 fix201ブランチをコンパイルしてみたところ、こちら報告させていただいた再現および手元の実プロジェクト共に、正常に動作することを確認しました！

尚、本件と近いバグをもう一件見つけたので、報告させてください（Issueの運用方針がわからないので書いちゃいますが、Issue別で起こした方がよければ改めて記載しますので仰ってください）

現象：以下のように、描画範囲やズーム比率がおかしくなるようです。

(状態A)
![2016-03-20 01 39 45](https://cloud.githubusercontent.com/assets/743292/13899905/b783ae7c-ee3c-11e5-9829-f1b562d26fb1.png)

(状態B)
![2016-03-20 01 38 01](https://cloud.githubusercontent.com/assets/743292/13899894/660c685e-ee3c-11e5-9891-805d55fa053f.png)

再現手順としては、以下の通りです。

1. 先のプロジェクトを、やはり1440x900など、足りない解像度の状態で起動する。
2. アプリケーションを起動したまま、Windowsのディスプレイ設定から、足りている解像度(1920x1080など)に変更する。
3. この時点で、状態Aになります。
3. 一度、吉里吉里をウィンドウモードに変更する。
4. もう一度、吉里吉里をフルスクリーンモードに変更する。
5. この時点で、状態Bになります。

滅多にない状況のようにも思うのですが、タブレットのタテヨコで解像度が自動設定されるような端末や母艦に繋ぐと大画面で使えるといったディスプレイなどでは、類似の状態が起きそうだなと思っています。

**Comment by jin1016** [comment]
fix201 マージしました。
上述の別問題は、別件のようですので別にissue起票していただけますでしょうか。

**Comment by AknEp** [comment]
承知しました、別途記載しますね。
