### ISSUE TITLE
ゲーム解像度よりも小さい画面解像度で起動した後、画面解像度を変更するとフルスクリーンでの描画が正しく行われなくなる

### ISSUE THREAD

**Issue by AknEp** [krkrz/krkrz#203]
## 現象

以下のように、描画範囲やズーム比率がおかしくなるようです。

(状態A)
![2016-03-20 01 39 45](https://cloud.githubusercontent.com/assets/743292/13899905/b783ae7c-ee3c-11e5-9829-f1b562d26fb1.png)

(状態B)
![2016-03-20 01 38 01](https://cloud.githubusercontent.com/assets/743292/13899894/660c685e-ee3c-11e5-9891-805d55fa053f.png)

## 再現手順

以下の通りです。

1. FullHDにしたプロジェクトを、やはり1440x900など、足りない解像度の状態で起動する。( https://github.com/4th-cluster/kag3/tree/oversize-representation などご利用ください )
2. アプリケーションを起動したまま、Windowsのディスプレイ設定から、足りている解像度(1920x1080など)に変更する。
3. この時点で、状態Aになります。
3. 一度、吉里吉里をウィンドウモードに変更する。
4. もう一度、吉里吉里をフルスクリーンモードに変更する。
5. この時点で、状態Bになります。

滅多にない状況のようにも思うのですが、タブレットのタテヨコで解像度が自動設定されるような端末や母艦に繋ぐと大画面で使えるといった端末などで、類似の状態が起きそうだなと思っています。

## 確認した環境

MacBook Pro Retina 13inch上のParallels Desktop 10.3.0 …の上のWindows10で再現

https://github.com/4th-cluster/kag3/tree/oversize-representation

**Comment by jin1016** [comment]
状態B は fix201 が入っていても(現在のmasterでも)起こりますか？
私の環境では再現しませんでしたが。
発生する場合、fix135 ブランチを適用して直っていませんか？

状態Aについては再現します。

**Comment by AknEp** [comment]
早速のお返事ありがとうございます！

最新の master ( cd39869d )に fix201 をmergeしたバージョンで確かめたところ、確かに状態Bが発生しなくなりました。 （fix201 の入っていないバージョンでは発生することも再確認しました） 同じ原因で起きていたということですね。

**Comment by jin1016** [comment]
同一ではなく、ついでに対応した以下のものによって修正されたのだと思われます。

> 従来はバックバッファの最大サイズはWindowのあるディスプレイの最大サイズとしていましたが、描画領域(クライアント領域)と比較して大きい方を指定して、描画されない領域が出ないようにしました。

後、報告時に最新のものや他のissueを確認していただけると手間が省けるので、事前確認していただけると助かります。

タブレットで画面回転による描画乱れは #98 で報告されているので、本件のフルスクリーン時の解像度変更と言うのは誰もしないと思われるので、私の方での対応は保留とします。

**Comment by AknEp** [comment]
> 後、報告時に最新のものや他のissueを確認していただけると手間が省けるので、事前確認していただけると助かります。

承知しました。目を通しておきますね。

保留と言うことで構わないかと思います。 closeして後で対応か、pendingのラベルにするかなど、本issueの今後の扱いはお任せします。

**Comment by jin1016** [comment]
#98 で汎用的な対応を行ったため、本問題も解決していると思いますので確認願います。
master に既にマージ済みなので、master で確認ください。

**Comment by AknEp** [comment]
入念に確認してみました。 完璧だと思います！
