### ISSUE TITLE
showModal ではアクティブにならない(?)

### ISSUE THREAD

**Issue by kiyobee** [krkrz/krkrz#210]
あるWindowをshowModalで表示したとき、アクティブにならないようです。
次のコードを実行して表示されたWindowをクリックすると子Windowがモーダル状態で表示されるのですが、onActivate が呼び出されません。onMouseWheelやIME切り替えができないので、onActivateが発生しないだけでなくアクティブになっていないと思われます。
該当の tTVPWindow::ShowModal() では SetActivateWindow が呼ばれているので、どの部分に問題があるのかちょっとわからない感じです。

```
class MyWindow extends Window
{
    var children = [];

    function MyWindow()
    {
        super.Window(...);
        name = "parent";
        add(new Layer(this, null));
        with(primaryLayer)
            .setSize(320, 240), setInnerSize(.width, .height);
    }

    function onClick()
    {
        var no = children.count;
        children.add(new global.MyWindow());
        children[no].name = name+".child["+no+"]";
//      children[no].visible = true; // activate
        children[no].showModal(); // not activate
    }

    function onActivate()
    {
        Debug.message(name+".onActivate()");
    }

    function onDeactivate()
    {
        Debug.message(name+".onDeactivate()");
    }
}
var win = new MyWindow();
win.visible = true;
```

**Comment by jin1016** [comment]
#178 #114 #112 
類件として上記issueが過去に上がっていて対応していますが、最新のバイナリはまだ上記対応が入っていなかったと思います。
現在のmasterのソースコードをビルドしても同様の問題が発生しますでしょうか？
現在編集等している手元のバイナリで確認したところonActivateの発生は確認できました。

**Comment by kiyobee** [comment]
すみません、確認不足だったようです。
PullしたソースでビルドしなおしてホイールとIMEのチェックを行い、意図通りの動作になっていることを確認しました。

**Comment by jin1016** [comment]
直っていましたか。良かったです。

ブランチで修正して、確認を待ってからマージしようと思っていたんですが、長期間確認が得られず、最近masterにマージしたものでした。
今後は、1週間程度待って確認連絡がない場合、自分の方で修正出来ていると確認できたものはマージしてしまおうと思います。
