### ISSUE TITLE
ウィンドウモード時に、ウィンドウを画面最上部にぶつけた時にonMaximizeQueryが発火してくれない

### ISSUE THREAD

**Issue by AknEp** [krkrz/krkrz#219]
こちら windowEx.dll 側の問題かもしれませんが…。

表題の通り、（Windows7だったか8だったかから出来るようになった？）ウィンドウを画面最上部にぶつけた時に発生する画面最大化処理で、Window.onMaximizeQuery が発火しないようです。
（もしくは、そもそも発火が不可能なのでしょうか？）

尚、onMaximizeは正しく発火しているようでした。

**Comment by miahmie** [comment]
windowEx.dllの件でしたら，onMaximizeQueryはWM_SYSCOMMANDでSC_MAXIMIZEが来た時のコールバックとなり，trueを返すとDefWindowProcを通さない仕様となります。
AeroSnapでの最大化でコールバックが来ないのはWM_SYSCOMMANDを通さないWindows側の仕様で，恐らく吉里吉里２でも同様の挙動になるかと思われます。
もし最大化を防止したいのであれば，borderStyle=bsSingle,bsDialogを使うか，setMaxSizeなどを使用して上限サイズを指定するなどしてください。

windowEx.dllのマニュアルにはこの件に関する補足を追記しておきます。（windowExは吉里吉里2のsvn側しかメンテしてないのでそちらの方のみの更新となりますが）

**Comment by AknEp** [comment]
なるほどなるほど、ありがとうございます。
そうすると、bsSizeableでWindows側の最大化を防ぐ方法は（Windows側の制約で）ない、ということですね。承知しました。
