### ISSUE TITLE
pを使った指数指定の動作がおかしい

### ISSUE THREAD

**Issue by sakano** [krkrz/krkrz#220]
TJSではpを使った指数表記が使えます。
http://krkrz.github.io/docs/tjs2/j/contents/token.html#id364
この動作が一部おかしいです。
吉里吉里2/Z共通の問題になります。

例えば以下のコードでは文法エラーが発生します。
<code>
System.inform(0b1p2);
</code>
これはトークンを切り分ける際にpの後ろが2進数として扱われており、2が数値の一部として認識されないためです。

また、次のコードでは0.5が表示されます。
<code>
System.inform(0x1pA);
</code>
トークンを切り分ける際にはpの後ろが16進数として扱われますが、切り分けたトークンをパースする際には10進数として扱われるためです。(現在の実装上'A'が-1になります)

コード上ではtjsLex.cppのTJSExtractNumberがトークンの切り分け、TJSParseNonDecimalRealがパースの該当箇所になります。

**Comment by sakano** [comment]
プルリクエストではpの後ろは10進数として扱うように修正しています。
指数を2進数や16進数で書きたい場面はあまり無いと思います。

**Comment by jin1016** [comment]
なぜpの後ろを常に10進数として扱わないのが問題なのかわからないのですが。

> 指数を2進数や16進数で書きたい場面はあまり無いと思います。

p以降を常に10進数として扱ってしまうと、指数を2進数や16進数で書くことが全くできなくなるわけで、それを是とする理由が思い当りません。
確か浮動小数点値をDic/Arrayなどで書き出す時、16進数の指数表現が使われていたと記憶しています。
10進数などで書き出してしまうと誤差が生じるためです。
そのためパースする方のみを変更すると書き出したものが読み出せないことになります。

**Comment by sakano** [comment]
> 確か浮動小数点値をDic/Arrayなどで書き出す時、16進数の指数表現が使われていたと記憶しています。
そういえば使われた気がします。

しかし現在でもpの後ろが正確に16進として解釈されているわけではないです。
例えば0x1p10は2^16ではなく2^10になります。
pの後ろが10進でも16進でもいいですが統一する必要はあるかと思います。

2進数でいうと問題点が分かりやすいと思いますが、0b1p10が2^10になるために2^2などをpで表記する手段がありません。

書き出し側はどうなっているのか分からないのでちょっと調査してみます。

**Comment by sakano** [comment]
Dictionary.saveStructでdoubleを書き出す際の動作について調査しました。

バイナリで書き出す際はdoubleのビット列がそのまま書き込まれるだけでp表記など使われません。

テキストで書き出す際はtjsVariant.cppのTJSRealToHexStringで文字列に変換したものを書き出しています。
pの後ろはdoubleの仮数部の数値の10進表記になっているようです。
16進とするには TJS_snprintf( t2, 128, TJS_W("%d"), exp); の部分を TJS_snprintf( t2, 128, TJS_W("%x"), exp); に変更することになります。


Dictionaryの書き出しを見る限りではpの後ろは10進数というのが本来の動作のように思います。


pの後ろを10進数に統一した場合の影響は以下のようになります。
* 0x1pAのような、A~Fを使っているコードが文法エラーになります。これまでは0xp-1と同じ数値になっていました。
* 0b1p2のような、2進数数値のpの後ろで2~9を使ったコードが文法エラーにならなくなります。
* 01p9のような、8進数数値のpの後ろで9を使ったコードが文法エラーにならなくなります。

pの後ろを16進数に統一した場合の影響は以下のようになります。
* 0x1pAのような、pの後ろでA~Fを使っているコードの実行時の数値が変わります。
* 0x1p10のような、pの後ろが2桁以上になっているコードの実行時の数値が変わります。おそらく既存のセーブデータがおかしくなります。

10進数に統一する方が影響が少ないと思いますがいかがでしょうか。

**Comment by jin1016** [comment]
X進数の指数を使った浮動小数点リテラルを持つ言語もしくはスクリプトを探したところC99が該当するようです。

参考:
[浮動小数点定数の 16 進数表記](http://seclan.dll.jp/c99d/c99d03.htm#dt19991206)
[浮動小数点数リテラル](http://www.tamasoft.co.jp/lc/hlp/F020.html)

この仕様ではpの後ろは10進数で表現することになっているので、既存の実装も考えると「pの後ろは10進数」が良さそうですね。
一応、元々はどういう仕様であったかDeeさんに確認してみようと思います。

**Comment by w-dee** [comment]
W.Deeです。

すみません、C99と同じ解釈が正しいです。

**Comment by jin1016** [comment]
プルリクエストマージ済みなので閉じてしまいますね
