### ISSUE TITLE
winnt.h の変更によるコンパイルエラーについて

### ISSUE THREAD

**Issue by pute293** [krkrz/krkrz#223]
Visual Studio Comm. v12 でコンパイルすると src/core/base/win32/SysInitImpl.cpp:612 でこけました。
winnt.h の FLOATING_SAVE_AREA のメンバ名が変わっている (Cr0NpxState -> Spare0) ことが原因です。
手元の環境では、WindowsKit/8.0/Include/um/winnt.h で Cr0NpxState、WindowsKit/8.1/Include/um/winnt.h で Spare0 になっています。

**Comment by jin1016** [comment]
現在サポートしているコンパイラは、VC2012 Pro です ( 将来 VC2015 Pro へ変更する可能性はあります )。
それ以外のコンパイラを使う場合は、ローカル等で自身で修正して行ってください。

**Comment by pute293** [comment]
了解です。
