### ISSUE TITLE
for 文の挙動について

### ISSUE THREAD

**Issue by pute293** [krkrz/krkrz#226]
for 文の初期化式を書く・書かないで for 文のスコープが変わりますが、これは想定された動作でしょうか？
- 挙動
```
var x = void, y = void;
for (var a = 0; a < 10; ++a) var x = a;
// for (...) { statement } として解釈され、
// x は void のまま
var b = 0;
for (; b < 10; ++b) var y = b;
// for (...) statement として解釈され、
// y は 9 になる
```

- 原因
src/core/tjs2/syntax/tjs.y の for_first_clause 内で呼ばれている tTJSInterCodeContext::EnterForCode が、初期化式が変数宣言でないときブロックを作らないため

- 提案
tTJSInterCodeContext::EnterForCode が常にブロックを生成するように変更し、上記挙動で y が void になるようにする

- 既存コードへの影響
破壊的変更であり、上記挙動に依存したコードが動かなくなる

**Comment by jin1016** [comment]
Deeさんに確認したところ、この動作は想定外とのことです。

修正とテストの労力に対して効果が全く釣り合わないため、私としてはこの動作は現状とします。
修正およびテストスクリプトのPRがあった場合、検証/受け入れはします。

**Comment by pute293** [comment]
ぎゃ、すみません、自分のレポジトリに push した履歴がこっちに残っちゃいました。
b1d7d76 （最後のやつ）以外は無視してください。

**Comment by jin1016** [comment]
確認しマージしました。
起票者と修正者が同じと言うことで、私の方で本件closeしておきます。
