### ISSUE TITLE
関数式の省略記法がほしい

### ISSUE THREAD

**Issue by pute293** [krkrz/krkrz#229]
`function (x) { return x * 2; }` のような小さな関数だと、関数本体に対して無駄な記述が多すぎるように思います。

他の言語でよく「ラムダ式（記法）」と呼ばれている、関数の省略記法がほしいです。
上記の例について、以下の形を提案します。

`-> (x) { return x * 2; }` 基本の書き方
`-> x { return x * 2; }` 引数なし・一引数なら丸括弧省略可
`-> x [ x * 2 ]` 本体が return 文のみなら return も省略可

いかがでしょうか。

**Comment by AknEp** [comment]
あくまで、一人のユーザーの意見として割り引いていただければ。

僕もrubyやES6やSwiftなどを業務で書いている経験から、確かにそういったシンタックスの向上は開発効率に寄与すると思います。が、吉里吉里Zではやるべきではないと思います。

そこまで仕様を拡張していってしまうと「吉里吉里2を大きく変えずにVisutal Studioでコンパイル出来るようにする」という吉里吉里Zのコンセプトから遠ざかるのではないでしょうか。
これを入れると、あれもこれもと、どんどん話が大きくなってしまう。

またTJS2のGCは循環参照するとリークするぐらいのものなので、ラムダの追加によって、この問題も踏みやすくなるのでは。（僕の記憶違いだったら済みません）

**Comment by jin1016** [comment]
提案にある文法は単純に function を -> に置き換えたものであり、基本の書き方では 6文字省略するものでしかなく、利便性は何も向上しない。
インテリセンス等のエディタ支援があれば、タイプ量節約の効果も薄くなる。
手軽に追加できると言うことで提案の文法になっていると思われるが、恒久的に導入するのであれば、文法的によく考慮されたものである形が望ましい。
以上の理由により、本文法は導入しない方が良いと考えます。

ES6 のラムダ式記法が TJS2 の辞書の記法と近いことから、もし導入すると言うことであれば、ES6 のラムダ式の形が望ましいです。
TJS2 にはブロックの最後の式の結果を返すことはしないはずなので、その部分に関しては別になると思いますが。

> そこまで仕様を拡張していってしまうと「吉里吉里2を大きく変えずにVisutal Studioでコンパイル出来るようにする」という吉里吉里Zのコンセプトから遠ざかるのではないでしょうか。

既に型指定等導入しているので、文法が分岐するからと言う理由で導入しないと言うことはしていません。
foreach 、パッケージ or モジュール、シリアライズ などが導入候補としてあります。

> またTJS2のGCは循環参照するとリークするぐらいのものなので、ラムダの追加によって、この問題も踏みやすくなるのでは。（僕の記憶違いだったら済みません）

TJS2 ドキュメントでは、名前のない関数、式中関数 ( 匿名関数 ) と書かれていますが、無名関数は既に TJS2 にあるので、この心配は無用です。

**Comment by pute293** [comment]
ご意見ありがとうございます。
話が大きくなって収拾がつかなくなると。

私としては

> 開発効率に寄与する

というところを重視したいところで、たとえば jin さんの初期の開発日誌を見ると TJS レベルでの機能追加要望も結構あって（このあたり：http://www.kaede-software.com/2013/04/post_609.html）、
また foreach 文のように issue (#217) で触れられている機能もあります。
こういうのはどんどん追加すべきだというのが私の考えです。

もちろんこの辺どこで線引きをするかは commiter の方の意向しだいですが、私としては、既存のコードに影響がない範囲で追加できる機能、特に構文糖の類ははどんどん追加していってほしいなあと考えています。

あと、メモリリークの件は問題ありません。あくまで構文糖なので、内部的には普通に関数式を書いたのと同じ処理になります。

**Comment by pute293** [comment]
jin さんのコメントがあったので追記です。

> ES6 のラムダ式記法が TJS2 の辞書の記法と近いことから、もし導入すると言うことであれば、ES6 のラムダ式の形が望ましいです。

仰る通りで、現在のパーサの処理内ではどうにも実装するのが難しそうということで提案の実装になりました。

Pull Request については、文法面で納得できないということですので取り下げます。
