### ISSUE TITLE
吉里吉里Z ver1.3にて、drawTextの挙動がおかしい。

### ISSUE THREAD

**Issue by toishi-hiroki** [krkrz/krkrz#240]
- ver 1.3.0.4 の32bit版、64bit版を使用すると、以下のようにdrawTextの文字描画がおかしくなります。

![ss](https://cloud.githubusercontent.com/assets/8639374/15942129/19c85134-2ebe-11e6-9656-bfdcaaf7a61a.png)

- 再現環境は以下の通りです。

OS: Windows 7 6.1.3505 Service Pack 1 (Win64)
CPU: Intel(R) Core(TM) i7-2600 
Total physical memory: 17161457664

- 再現コードは以下の通りです。

```
class TestWindow extends Window
{
	function TestWindow()
	{
		Window();
		borderStyle = bsSingle;
		add(new Layer(this, null));

		primaryLayer.font.face = "メイリオ";
		primaryLayer.font.height = 32;
		primaryLayer.font.bold = true;

		setInnerSize(1280, 720);
		visible = true;
	}

	function onResize()
	{
		primaryLayer.setSize(innerWidth, innerHeight);
		primaryLayer.fillRect(0, 0, primaryLayer.width, primaryLayer.height, 0xffaaaaaa);
		primaryLayer.drawText(10, 10, "0123456789 ABCDEFGHIJKLMNOPQRSTUVWXYZ", 0xff8888, 255, true, 5000, 0x222222, 3, 1, 1);
		primaryLayer.drawText(10, 50, "あいうえおかきくけこさしすせそたちつてと", 0xff8888, 255, true, 5000, 0x222222, 3, 1, 1);
		primaryLayer.drawText(10, 90, "〇一二三四五六七八九・晴耕雨読・臥薪嘗胆", 0xff8888, 255, true, 5000, 0x222222, 3, 1, 1);
	}
}

var win = new TestWindow();
```

**Comment by jin1016** [comment]
shadowlevel の値が大きいと桁あふれが発生して白が出てしまっているようです。
開発中も認識していたものの一般的な使用範囲では問題ないと考えていました(従来も大きくしすぎると同様の問題が発生するため)。
非 SSE2 版では添付されたスクリプトでは発生しないため、C版と同程度の演算精度のバージョンも準備し、一定値で切り替えることにします。
boxblur も同様の処理を行っているので。
記憶では、従来はこの処理の MMX 版はなかったと思うので、単純に SSE2 版を抑止するだけでも解決しますが。

**Comment by jin1016** [comment]
修正したので確認をお願いします。
masterに入っています。
ビルド環境がない場合は先にバグフィックス版出します。

**Comment by toishi-hiroki** [comment]
修正ありがとうございます。ビルドして確認させていただきました。
同一のスクリプトで白抜けすることなく文字が描画されていることを確認しました。
ただ、今回確認していて別途気付いてしまったのですが、

![-1](https://cloud.githubusercontent.com/assets/8639374/17046631/6b5ec938-5010-11e6-89d3-625aa996f528.jpg)

ver1.2 と ver1.3 で、同一スクリプトを使っているにも関わらず文字描画が若干異なります。
どうやら文字のシャドウが左右1ドットずつ削れてしまっているようです。
文字「C」や「D」の辺りで顕著に確認できます（ver1.3 では隙間ができてしまっている）。
以上、ご報告でした。

**Comment by jin1016** [comment]
修正し、masterへ入れました。
確認をお願いします。

elseの中括弧忘れというケアレスミスでした。
そのせいでなかなか見つけられず……

**Comment by toishi-hiroki** [comment]
修正ありがとうございます。ビルドして確認させていただきました。
今回の修正を適用したところ、ver1.2 と同じ描画結果が得られました。
問題なく修正されているように思います！
以上、ご報告でした。

**Comment by jin1016** [comment]
確認ありがとうございます。
修正済みと言うことで閉じますね。
