### ISSUE TITLE
バージョン1.3.1.5 (32bit版)において動画ファイルのオープン時に異常終了する

### ISSUE THREAD

**Issue by kashiwam0chi** [krkrz/krkrz#241]
吉里吉里Z 1.3.1.5( http://krkrz.github.io/download/krkrz_20160603.7z )の32bit版において、
動画ファイルのオープン時に吉里吉里本体が異常終了してしまいます。

■再現スクリプト
```javascript
class TestWindow extends Window
{
	var lay;
	var vol;
	
	function TestWindow()
	{
		super.Window();
		
		add(lay = new Layer(this, null));
		
		lay.setSize(1280, 720);
		setInnerSize(1280, 720);
		visible = true;
		
		add(vol = new VideoOverlay(this));
		
		with (vol)
		{
			.mode = vomMFEVR;
			//.mode = vomOverlay;
			//.mode = vomLayer;
			
			.layer1 = lay;
			
			.open("test1.mp4");
			//.open("test2.wmv");
			//.open("test3.mpg");
		}
	}
}

var win = new TestWindow();
```

異常終了することが確認できた動画フォーマットと描画モードの組み合わせは以下の通りとなります。
※Theoraについては未確認、MPEG-1については正常にオープンおよび再生できております。
- H.264 (vomMFEVR)
- WMV9  (vomMFEVR, vomOverlay, vomLayer)

なお、vomOverlayおよびvomLayerでは以下のメッセージが表示されています。
※vomMFEVRの場合、メッセージが表示されずそのままクラッシュします。
![image](https://cloud.githubusercontent.com/assets/19360569/16355893/af204752-3b00-11e6-9d41-52a74b0e887a.png)

**Comment by jin1016** [comment]
32bit版でMediaFoundationを使うか、WMVを再生しようとすると発生するようです。
64bit版か、MPEG 1、Theoraでは発生しませんでした。
MPEG 1とTheoraで確認していたので、気付きませんでした。

確認すると呼び出し規約の問題のようです。
krmovieはstdcallでビルドされていましたが、本体はcdeclでビルドされています。
DLLからの取得したメソッドを呼び出し規約を指定せずにキャストして呼び出していたため、ビルドオプションの呼び出し規約でAPIが呼び出されていましたが、従来はstdcallで問題なく、本体に統合されるとcdeclで呼び出され落ちていたようです。
64bitでは呼び出し規約は1つなので問題は発生していません。

ちなみにOverlayは、実質的にobsolate扱いです。Mixerを使ってください。

**Comment by jin1016** [comment]
修正してmasterにマージしました。
確認をお願いします。

**Comment by kashiwam0chi** [comment]
手元の環境にてmaster上のソースコードをビルドし、上記不具合が修正されていることを確認いたしました。
ご対応ありがとうございます。
