### ISSUE TITLE
krkrz ltAddAlpha issue

### ISSUE THREAD

**Issue by Doutei** [krkrz/krkrz#243]
Situation:
Background <- messagelayer on top of it <- pagebreak (or linebreak) on top of messagelayer
![krkr_report](https://dl.dropboxusercontent.com/u/110558786/Report/krkrz/krkr_report.png)

Why this happens? Is this a bug?
You can get [source files](https://dl.dropboxusercontent.com/u/110558786/Report/krkrz/krkr_files.zip) here.

Edit:
krkrz 1.3.5.1 --> Wrong Output
krkrz 1.3.0.4 --> Wrong Output
krkrz 1.2.0.3 --> Correct Output
krkrz 1.1.0.2 --> Correct Output

**Comment by jin1016** [comment]
It was fixed this bug.
please confirm.

**Comment by Doutei** [comment]
@jin1016 It was fixed! v1.3.2.6 is correct. Thank you!
