### ISSUE TITLE
吉里吉里Z 1.3.x.xでstretchCopyを実行するとエラー

### ISSUE THREAD

**Issue by tori123** [krkrz/krkrz#248]
吉里吉里Zの 1.3.1.5 と 1.3.0.4 で、layer の stretchCopy() を
実行すると、「Illegal Instruction：無効な命令を実行しようと
しました」というダイアログが表示されます。
吉里吉里Z 1.2.0.3 以前のバージョンなら問題なく動作し、また
Win7 Home/Professional の別マシンではいずれも問題なく動作
しました。

OS : Windows 7 Starter (32bit) Service Pack 1
CPU: Intel(R) Atom(TM) CPU N455   @ 1.66GHz
Mem: 1GB
ハードウェア：FMV LIFEBOOK MH20/C

first.ks中で、以下のtjsスクリプトを実行すると再現します。

--------------------------------------------

var l1 = new Layer(kag, kag.primaryLayer);
var l2 = new Layer(kag, kag.primaryLayer);
l1.setImageSize(800,600);
l2.setImageSize(160,120);
l2.stretchCopy(0,0, l2.imageWidth,l2.imageHeight,
               l1, 0,0, l1.imageWidth, l1.imageHeight,
               stLinear);

--------------------------------------------

起動時メッセージの冒頭は以下の通りです。

01:28:36 ! 吉里吉里[きりきり] Z 実行コア/1.3.1.5 (Compiled on May 31 2016 17:29:53) TJS2/2.4.28 Copyright (C) 1997-2013 W.Dee and contributors All rights reserved.
01:28:36 ! バージョン情報の詳細は -about を付けて起動すると閲覧できます
01:28:36 ! Windows 7 6.1.3505 Service Pack 1 (Win32) 上で実行が開始されました
01:28:36 ! (info) Total physical memory : 1062649856
01:28:36 ! (info) Selected project directory : file://./c/users/torii1060/desktop/krkrz/data/
01:28:36 ! (info) CPU #0 :   FPU:yes  MMX:yes  3DN:no  SSE:yes  CMOVcc:yes  E3DN:no  EMMX:yes  SSE2:yes  TSC:yes  TSCP:no  SSE3:yes  SSSE3:yes  SSE41:no  SSE42:no  SSE4A:no  AVX:no  AVX2:no  FMA3:no  AES:no  RDRAND:no  RDSEED:no  Intel(GenuineIntel) [         Intel(R) Atom(TM) CPU N455   @ 1.66GHz]  CPUID(1)/EAX=000106CA CPUID(1)/EBX=00020800
01:28:36 ! (info) CPU #1 :   FPU:yes  MMX:yes  3DN:no  SSE:yes  CMOVcc:yes  E3DN:no  EMMX:yes  SSE2:yes  TSC:yes  TSCP:no  SSE3:yes  SSSE3:yes  SSE41:no  SSE42:no  SSE4A:no  AVX:no  AVX2:no  FMA3:no  AES:no  RDRAND:no  RDSEED:no  Intel(GenuineIntel) [         Intel(R) Atom(TM) CPU N455   @ 1.66GHz]  CPUID(1)/EAX=000106CA CPUID(1)/EBX=01020800
01:28:36 ! (info) finally detected CPU features :   FPU:yes  MMX:yes  3DN:no  SSE:yes  CMOVcc:yes  E3DN:no  EMMX:yes  SSE2:yes  TSC:yes  TSCP:no  SSE3:yes  SSSE3:yes  SSE41:no  SSE42:no  SSE4A:no  AVX:no  AVX2:no  FMA3:no  AES:no  RDRAND:no  RDSEED:no
01:28:36 ! (info) Specified option(s) (earlier item has more priority) : (none)
01:28:36 ! OS : Windows 7 6.1.3505 Service Pack 1 (Win32)
01:28:36 ! KAG : 3.30 stable
01:28:36 ! Kirikiri : 1.3.1.5
01:28:37 ! (info) CPU clock (roughly) : 1640MHz
01:28:39 ! wuvorbis: SSE enabled. MMX enabled. 3DNow! disabled.

------

エラー時の EIP のコードは以下の通りです。

01:28:40 Codes at EIP : 0x66 0x0F 0x38 0x2B 0xC0 0x66 0x0F 0x67 0xC0 0x66 0x0F 0x7E 0x41 0xFC 0x46 0x89 0x4D 0x08 0x8B 0x4D 0xFC 0x0F 0x57 0xC0 0x3B 0x75 0x10 0x0F 0x8C 0x32 0xFF 0xFF 0xFF 0x5F 0x5E 0x8B 0xE5 0x5D 0xC2 0x10 0x00 0xCC 0xCC 0xCC 0xCC 0xCC 0xCC 0xCC 0xCC 0xCC 0xCC 0x53 0x8B 0xDC 0x83 0xEC 0x08 0x83 0xE4 0xF0 0x83 0xC4 0x04 0x55 0x8B 0x6B 0x04 0x89 0x6C 0x24 0x04 0x8B 0xEC 0x83 0xEC 0x48 0x8B 0x41 0x30 0x8B 0x53 0x08 0x66 0x0F 0x6F 0x05 0xB0 0x03 0x63 0x00 0x56 0x8B 0x73 0x18 0x57 0x8B

必要であれば起動時からのログをすべてお送りします。

------
stLinear を stNearest に変更すると動作する事も確認できました。

**Comment by jin1016** [comment]
手持ちのPCの中で再現するものがあったので、解析進められそうです。
サポートされていないSIMD命令(SSE4x辺り)を実行してしまっているではないかと推測されます。

**Comment by jin1016** [comment]
修正し、masterへ入れました。
ビルドできる場合はビルドして確認をお願いします。
出来ない場合は、他のいくつかの修正が完了後バグフィックス版を出すのでそちらで確認をお願いします。

**Comment by tori123** [comment]
お早い対応ありがとうございました。
私には難しそうでしたので、BugFix版を待ちたいと思います。

**Comment by jin1016** [comment]
バグフィックス版の1.3.2をリリースしました。ご確認ください。

**Comment by tori123** [comment]
修正お疲れ様でした。
先ほど試させて頂いた所問題なく起動することが出来ました。
本当にありがとうございました！
