### ISSUE TITLE
Layer.affineCopy()実行時、ハードウェアエラーが発生することがある。

### ISSUE THREAD

**Issue by ksn923** [krkrz/krkrz#253]
[問題点]
Layer.affineCopy()実行時、ハードウェアエラーが発生することがある。
吉里吉里Z 1.3.#.# でのみ確認。吉里吉里Z 1.2.# や吉里吉里2では
起こらない模様。吉里吉里Z 1.3.2.6でも発生。
下の再現スクリプトを実行しても、起こったり起こらなかったりする。
#237 と関連があるかもしれない。

[OS]
Win7 Home/Professional で確認

[CPU]
Core i7 3660S および Core i5 2520M で確認

[再現スクリプト(ただし問題が起こらないこともある)]
; KAGシステム上での場合。そのほかの場合は適当にwindow/layerを変更
var src = new Layer(kag, kag.fore.base);
var dst = new Layer(kag, kag.fore.base);
src.setImageSize(512,512);
dst.setImageSize(32, 32);
dst.affineCopy(src, 0, 0, 64, 64, true,		
0.0082030296974481, 0.0933904320783601, -0.0933904320783601, 0.0082030296974481, 5.72599687618918, -0.250990776825861,
		stNearest, true);

**Comment by ksn923** [comment]
すみません、今手元で再確認したら、1.3.2.6 では発生せず、その他の 1.3.x では
発生しました。もしかしたら #237 で修正された問題かもしれません。
そうであれば duplicated として close してください。

**Comment by jin1016** [comment]
1.3.2.6 で発生しないと言うことであれば、起票者側で閉じていただけますか？

**Comment by ksn923** [comment]
偶然の別件の可能性があるかと思いましたが、わかりました。では close します。

**Comment by jin1016** [comment]
偶然の別件も何も発生しないようなものをどう調査するのですか？
同件だったとして、調査確認に数時間から数日かかりますが、その手間を今発生しなくなっているものに費やすのですか？

まだ発生するのかどうか、直っているかどうか十分に確認して、私に無駄な工数が発生しないようにしていただけると、Android版等の開発が進むので、その点考慮願います。
