### ISSUE TITLE
Source file encoding

### ISSUE THREAD

**Issue by vToMy** [krkrz/krkrz#261]
Currently most source files (`.h`, `.cpp`) are encoded using `shift-jis`, and users of other locales can't view the Japanese comments in the code. More importantly, it also causes compilation errors:
![screenshot 2016-08-11 18 16 56](https://cloud.githubusercontent.com/assets/6370957/17593891/131195cc-5ff0-11e6-95c5-e8aeaa425901.png)
You can see the 4th line is commented out since the encoding issue generates a blackslash in the line above it.

Some source files have different encoding:
*UTF-16le*
`external\jxrlib\common\include\guiddef.h`
`external\jxrlib\common\include\wmsal.h`
`external\jxrlib\common\include\wmspecstrings_adt.h`
`external\jxrlib\common\include\wmspecstrings_strict.h`
`external\jxrlib\image\sys\ansi.h`
`external\jxrlib\image\sys\xplatform_image.h`
`vc2012\resource.h`
*ANSI (that's not really an encoding, but it's what notepad++ says)*
`external\jxrlib\common\include\wmspecstring.h`
`external\jxrlib\common\include\wmspecstrings_undef.h`

I suggest converting all the source files to Unicode - either UTF-8 or UTF-16le.
I can create a pull request for it, just need to know which encoding you prefer.
Here's a comparison of the number of bytes used per character:
UTF-8: English - 1 byte, Japanese - 3 bytes
UTF-16: English - 2 bytes, Japanese - 2-4 bytes (4 being more rare)

I suggest using UTF-8 as most source code is English and it's pretty much standard.
This change will not affect developers that doesn't have this problem, as will VS recognize and load the files with the correct encoding.

**Comment by jin1016** [comment]
I translated to UTF-8(without BOM).
It use Visual Studio 2015 Update 2 or later.
The external library has been moved to the submodule.
When you clone repository, you must update/initialize the submodule.

ソースコードを UTF-8 に変換しました。
それに伴い プロジェクトファイルも Visual Studio 2015 Update 2 以降用になりました。
外部ライブラリ類はサブモジュール化しました。
cloneする時、同時にサブモジュールのアップデート/初期化が必要です。

**Comment by vToMy** [comment]
Thanks a lot. The project now compiles properly.
