### ISSUE TITLE
Can not generate stub file.

### ISSUE THREAD

**Issue by yaqinking** [krkrz/krkrz#264]
I have been installed perl from https://www.activestate.com/activeperl/downloads , but when I run `makestub.bat` It report errors.

```
C:\krkrz\base\win32>perl makestub.pl
\C no longer supported in regex; marked by <-- HERE in m//\*\[C\*/(.*?)/\*\ <--
HERE C]\*// at makestub.pl line 327.
```

I have no idea to solve this...

System: Windows7 64bit

**Comment by jin1016** [comment]
ソースコードをUTF-8化した時に即座に必要と言うわけではないため、まだmakestub.plの更新は行われていません。
https://github.com/krkrz/krkrz/tree/last_hodgepodge_repository ブランチにある、tp_stub.h/cpp を利用してください。

**Comment by yaqinking** [comment]
It works. Thank you!
