### ISSUE TITLE
the new TJS_snprintf not support %I64d

### ISSUE THREAD

**Issue by freshairboom** [krkrz/krkrz#268]
when you format a string with %d, tjs parser will convert it to %I64d, but new snprintf not support %I64d

new snprintf is update by this commit:https://github.com/krkrz/krkrz/commit/e492bda927d3c7d58967d76f082b73d8949944ff

![snipaste20161229_020726](https://cloud.githubusercontent.com/assets/6312139/21528196/ae0ebca6-cd6b-11e6-9966-3f9c843b6742.jpg)

tjsVariantString.cpp: 899 line

just for test:

> with (new Date()) System.inform("%04d/%02d/%02d %02d:%02d:%02d".sprintf(.getYear(),  .getMonth() + 1, .getDate(), .getHours(), .getMinutes(),   .getSeconds()));

**Comment by jin1016** [comment]
dev_multi_platform は開発途中のブランチです。
鬱陶しいのでまだ不具合報告しないでください。
