### ISSUE TITLE
Texture の Bitmap 指定のコンストラクタ

### ISSUE THREAD

**Issue by wtnbgo** [krkrz/krkrz#279]

**Comment by wtnbgo** [comment]
Win 版で new Texture(bitmap) した時に ARGB でなく ABGR として反映されます。
texture.copyRect(bitmap) した場合は期待通りに動作します

**Comment by jin1016** [comment]
修正しました。ご確認ください。

**Comment by wtnbgo** [comment]
無事修正されてました。ありがとうございます
