### ISSUE TITLE
Font Stopped Working

### ISSUE THREAD

**Issue by year2000** [krkrz/krkrz#281]
Hi. I'm still a beginner, so I apologize if this is a dumb question.

I was using a .tft file I made from a .ttf and everything was working fine until I accidentally deleted some of the files in the savedata folder. However, even when I restored them the font didn't load. `"chDefaultFace" => "sourcehanheavy.tft",` still appears in datasc.ksd, but the font looks like this.

![image](https://user-images.githubusercontent.com/35497725/35187856-c7c46216-fdf0-11e7-864b-9fb8eeaeabd1.png)

In config.tjs, I have `;userFace = "sourcehanheavy.tft";` written, and in afterinit.ks I have the following:

> `Plugins.link("addFont.dll");`
> `var fontfilename = "sourcehanheavy.tft";`
> `System.addFont(fontfilename, true);`

I'm using the addFont.dll provided with Kirikiri 2. I doubt that's the problem, though, because like I said it was working fine before I deleted the savedata files.

I even tried a reinstall to a different folder (this time using KAG3_Ham) and repeated the steps that worked, but when I try that tvpwin64 gives me an error saying it can't load addFont.dll.

Is there any way to fix my first problem, and maybe even use it with KAG3_Ham?

**Comment by jin1016** [comment]
Since tvpwin64 is a 64bit program, 64bit dll is required.
Kirikiri2 plugins is a 32bits.
I think it will work if running with tvpwin32.

**Comment by year2000** [comment]
In the first installation that used the template from kag3-master.zip, tvpwin64 had been working with addFont.dll up until I deleted and then restored data1.ksd, data999.ksd, data1000.ksd, and datasc.ksd. It still runs now, the only thing different is that the font isn't working.

As for the KirikiriZ that uses kag3_ham-master.zip, the one that couldn't load the plugin, even when I use tvpwin32 I get this:

![image](https://user-images.githubusercontent.com/35497725/35197226-1d4bc326-fea2-11e7-96b5-f4793d664e66.png)

**Comment by year2000** [comment]
@vToMy Normally I'd agree, but `userFace` used to work with the file name, and even when I did set it to the font name to see if that was actually the problem it didn't work. (Also .tfts can't really be read by anything other than Kirikiri, so I can't view it by double-clicking like a .ttf or an .otf.)

![image](https://user-images.githubusercontent.com/35497725/35486177-f55ab10e-042f-11e8-8db4-b45d6969e939.png)

Obviously I also tried using a .ttf and .otf since KirikiriZ can apparently read those too, but still had no luck. It doesn't work even when I set it to Meiryo.

I don't really know if there's anything else to try.

@jin1016 また邪魔して本当に申し訳ありませんが、私が間違えましたなら教えてくれませんか？諦めるの前に確かめたいのです。すみませんでした。

**Comment by jin1016** [comment]
"sourcehanheavy.tft"がレンダリング済みフォントを指しているのであれば、"addFont.dll"は不要です。
Font.mapPrerenderedFontによって現在使用しているフェイス名にレンダリング済みフォントを割り当てて使用する必要があります。

レンダリング済みフォントデータ作成ツールについて
https://krkrz.github.io/krkr2doc/kr2doc/contents/FontMaker.html

Font.mapPrerenderedFont
http://krkrz.github.io/docs/kirikiriz/j/contents/f_Font_mapPrerenderedFont.html

---

If "sourcehanheavy.tft" is a rendered font, "addFont.dll" is unnecessary.
In that case you need to use Font.mapPrerenderedFont.
Font.mapPrerenderedFont assigns the rendered font to the current face name.

**Comment by year2000** [comment]
@jin1016 ごめんなさい。まだ狼狽しています。
Font.mapPrerenderedFontをどこに入ればいいのですか？KAGスクリプト分かりません。私が初心者って明白だと思いましたが…苦笑
まあ構いません。一番知りたいことは、なぜこの前にちゃんと作動しましたのか。
[これ](http://yue0630usa.blog.fc2.com/blog-entry-22.html)の例コードを使いました。tvpwin64さえも作動しました。tftですけどaddFont.dllを使えました。問題はdatasu.ksdを削除した後に始めました。

本当に吉里吉里を使いたいです。悲しいです( ﾉ＿；`)

**Comment by jin1016** [comment]
初心者を免罪符にしてただ質問だけする人にこれ以上付き合う気はありません。
TJS2スクリプトを少しでも理解できるよう勉強して、もっと自分で調べてください。
このissueはもう閉じます。

**Comment by nightpool** [comment]
Unfortunately, the mapPrerenderedFont call does not work with inline italics text common in English. Is there a 64-bit version of addFont.dll available?
