### ISSUE TITLE
Debug.console & Debug.controller do not exist

### ISSUE THREAD

**Issue by onlu-gh** [krkrz/krkrz#299]
Hi,
When trying to show the debug console and/or the debug controller I get an exception thrown saying that 'console' and 'controller' are not members of 'Debug'.

Code:
```
//both of these commands throw the exception
Debug.console.visible = true;
Debug.controller.visible = true;
```

I would like to resolve this issue as I have no other means of line-by-line debugging.
Thanks.

**Comment by jin1016** [comment]
吉里吉里Zでは console と controller は削除しました。
console はコマンドラインに表示されるので、コマンドラインから吉里吉里Zを起動してください。

デバッガである krkrdebg.exe を使用したデバッグを検討してください。
吉里吉里Z では、本体側からデバッグ機能を減らしてクラック体制を高め、デバッガによる効率的なデバッグを行えるようにする方向性です。

**Comment by onlu-gh** [comment]
Thanks for responding.
Let me apologize for the time it took me to reply, I didn't realize you responded as I expected to get notified by GitHub but didn't.

I'm gonna try krkrdebg.exe and see how that goes.

**Comment by onlu-gh** [comment]
After running, I get this error :

![image](https://user-images.githubusercontent.com/36589091/107429290-6d373600-6b2c-11eb-8d92-5c97b2cfc468.png)

what does it indicate?

**Comment by jin1016** [comment]
Please let us know what steps you took.

**Comment by onlu-gh** [comment]
The steps I took:
1. put krkrdebg.exe and debugger.sdp in my root folder
2. opened krkrdebg.exe
3. let it load my project files
4. pressed the green run button

Contents of startup.tjs:
![image](https://user-images.githubusercontent.com/36589091/107444299-ffe2cf80-6b42-11eb-8dcb-9bec40e10798.png)

**Comment by onlu-gh** [comment]
Ok, I got it to work after looking at the documentation and changing a few settings:
1. removed the -readencoding Shift_JIS command line argument (left only -debug)
2. changed script encoding to UTF-8
Thanks for the help, this is going to be really useful for the development process 👍
